# version: "3.9"

services:
  backend:
    build: .
    container_name: Cbv
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./:/app
    ports:
      - "8000:8000"
    environment:
      SECRET_KEY: django-insecure-rh)10532-c8@@tz)gu$1*f*ff%1%3(&xvs#h8xqy$neo2q)4n0
      DEBUG: "True"
